"use client";

import { useState } from "react";
import { type LeadStage, type QuoteStatus, type TaskStatus } from "@prisma/client";
import {
  RegistrationBadge,
  StageBadge,
  QuoteBadge,
  STAGE_LABELS,
  QUOTE_LABELS,
  taskStatusLabel,
} from "@/components/Badges";
import { type LeadWithRelations } from "@/types/lead";

const STAGE_OPTIONS = Object.keys(STAGE_LABELS) as LeadStage[];
const QUOTE_OPTIONS = Object.keys(QUOTE_LABELS) as QuoteStatus[];
const TASK_OPTIONS: TaskStatus[] = ["DEALER_TODO", "DEALER_DONE", "CORDON_TODO", "CORDON_DONE"];

export default function LeadDetail({
  lead,
  role,
  onUpdated,
}: {
  lead: LeadWithRelations;
  role: "DEALER" | "INTERNAL_ADMIN";
  onUpdated: () => void;
}) {
  const [registrationDate, setRegistrationDate] = useState(lead.registrationDate.slice(0, 10));
  const [stage, setStage] = useState<LeadStage>(lead.stage);
  const [quoteStatus, setQuoteStatus] = useState<QuoteStatus>(lead.quoteStatus);
  const [quotedAt, setQuotedAt] = useState(lead.quotedAt ? lead.quotedAt.slice(0, 10) : "");
  const [quoteValueGbp, setQuoteValueGbp] = useState(lead.quoteValueGbp?.toString() ?? "");
  const [roiToBeDiscussed, setRoiToBeDiscussed] = useState(
    lead.roiToBeDiscussed === null ? "" : lead.roiToBeDiscussed ? "yes" : "no"
  );
  const [productOptionsStatus, setProductOptionsStatus] = useState<TaskStatus | "">(
    lead.productOptionsStatus ?? ""
  );
  const [solidHoppers, setSolidHoppers] = useState(lead.solidHoppers?.toString() ?? "");
  const [liquidLines, setLiquidLines] = useState(lead.liquidLines?.toString() ?? "");
  const [flowBoost, setFlowBoost] = useState(
    lead.flowBoost === null ? "" : lead.flowBoost ? "yes" : "no"
  );
  const [buyingProcess, setBuyingProcess] = useState(lead.buyingProcess ?? "");
  const [finalApprover, setFinalApprover] = useState(lead.finalApprover ?? "");
  const [closedLostReason, setClosedLostReason] = useState(lead.closedLostReason ?? "");
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const isAdmin = role === "INTERNAL_ADMIN";

  async function patchLead(body: Record<string, unknown>) {
    setSaving(true);
    setError(null);
    const res = await fetch(`/api/leads/${lead.id}`, {
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(body),
    });
    setSaving(false);
    if (!res.ok) {
      const data = await res.json().catch(() => ({}));
      setError(data.error || "Update failed.");
      return false;
    }
    onUpdated();
    return true;
  }

  async function handleSavePipeline() {
    await patchLead({
      registrationDate: new Date(registrationDate).toISOString(),
      stage,
      quoteStatus,
      quotedAt: quotedAt ? new Date(quotedAt).toISOString() : null,
      quoteValueGbp: quoteValueGbp ? Number(quoteValueGbp) : null,
      roiToBeDiscussed: roiToBeDiscussed === "" ? null : roiToBeDiscussed === "yes",
      productOptionsStatus: productOptionsStatus || null,
      solidHoppers: solidHoppers ? Number(solidHoppers) : null,
      liquidLines: liquidLines ? Number(liquidLines) : null,
      flowBoost: flowBoost === "" ? null : flowBoost === "yes",
      buyingProcess: buyingProcess || null,
      finalApprover: finalApprover || null,
      closedLostReason: closedLostReason || null,
    });
  }

  async function handleApprove() {
    setSaving(true);
    setError(null);
    const res = await fetch(`/api/leads/${lead.id}/approve`, { method: "POST" });
    setSaving(false);
    if (!res.ok) {
      const data = await res.json().catch(() => ({}));
      setError(data.error || "Approval failed.");
      return;
    }
    onUpdated();
  }

  async function handleReject() {
    await patchLead({ registrationState: "REJECTED" });
  }

  return (
    <div className="space-y-5 border-t border-navy-100 bg-navy-50/40 p-5">
      <div className="grid gap-4 sm:grid-cols-3">
        <div>
          <label className="label">Contact</label>
          <p className="text-sm text-navy">{lead.legalName}</p>
          <p className="text-sm text-navy-400">{lead.phone || "No phone on file"}</p>
          <p className="text-sm text-navy-400">{lead.email || "No email on file"}</p>
        </div>
        <div>
          <label className="label">Submitted by</label>
          <p className="text-sm text-navy">{lead.dealer.name}</p>
          {lead.leadGeneratorName && (
            <p className="text-sm text-navy-400">Generated by {lead.leadGeneratorName}</p>
          )}
          <p className="text-sm text-navy-400">{new Date(lead.createdAt).toLocaleString()}</p>
        </div>
        <div>
          <label className="label">Cordon status</label>
          <RegistrationBadge state={lead.registrationState} />
          {lead.expiresAt && (
            <p className="mt-1 text-xs text-navy-400">
              Exclusivity expires {new Date(lead.expiresAt).toLocaleDateString()}
            </p>
          )}
        </div>
      </div>

      {isAdmin && lead.registrationState === "PENDING" && (
        <div className="space-y-3 rounded-sm border border-orange-200 bg-orange-50 p-4">
          <p className="text-sm font-semibold text-navy">
            Approval decision needed — check for other dealers on the same farm.
          </p>
          <div className="flex flex-wrap gap-2">
            <button className="btn-accent" disabled={saving} onClick={handleApprove}>
              Approve (clears any conflicting registrations)
            </button>
            <button className="btn-outline" disabled={saving} onClick={handleReject}>
              Reject
            </button>
          </div>
        </div>
      )}

      <div className="grid gap-4 sm:grid-cols-2">
        <div>
          <label className="label">Registration date</label>
          <input
            type="date"
            className="input"
            value={registrationDate}
            onChange={(e) => setRegistrationDate(e.target.value)}
          />
        </div>
        <div>
          <label className="label">Client stage</label>
          <select
            className="input"
            value={stage}
            onChange={(e) => setStage(e.target.value as LeadStage)}
          >
            {STAGE_OPTIONS.map((s) => (
              <option key={s} value={s}>
                {STAGE_LABELS[s]}
              </option>
            ))}
          </select>
        </div>
        {stage === "CLOSED_LOST" && (
          <div className="sm:col-span-2">
            <label className="label">Reason lost</label>
            <input
              className="input"
              placeholder="Why this one didn't close"
              value={closedLostReason}
              onChange={(e) => setClosedLostReason(e.target.value)}
            />
          </div>
        )}
        <div>
          <label className="label">Quote status</label>
          <select
            className="input"
            value={quoteStatus}
            onChange={(e) => setQuoteStatus(e.target.value as QuoteStatus)}
          >
            {QUOTE_OPTIONS.map((q) => (
              <option key={q} value={q}>
                {QUOTE_LABELS[q]}
              </option>
            ))}
          </select>
        </div>
        <div>
          <label className="label">Date quoted</label>
          <input
            type="date"
            className="input"
            value={quotedAt}
            onChange={(e) => setQuotedAt(e.target.value)}
          />
        </div>
        <div>
          <label className="label">Quote value (GBP)</label>
          <input
            type="number"
            min="0"
            step="0.01"
            className="input"
            value={quoteValueGbp}
            onChange={(e) => setQuoteValueGbp(e.target.value)}
          />
        </div>
        <div>
          <label className="label">ROI to be discussed?</label>
          <select
            className="input"
            value={roiToBeDiscussed}
            onChange={(e) => setRoiToBeDiscussed(e.target.value)}
          >
            <option value="">Not set</option>
            <option value="yes">To be discussed</option>
            <option value="no">Not needed</option>
          </select>
        </div>
        <div>
          <label className="label">Buying process identified</label>
          <input
            className="input"
            placeholder="e.g. committee vote, single owner decision"
            value={buyingProcess}
            onChange={(e) => setBuyingProcess(e.target.value)}
          />
        </div>
        <div>
          <label className="label">Final approval by</label>
          <input
            className="input"
            placeholder="Who has the final say"
            value={finalApprover}
            onChange={(e) => setFinalApprover(e.target.value)}
          />
        </div>
      </div>

      <div className="rounded-sm border border-navy-100 bg-white p-4">
        <p className="mb-3 text-sm font-semibold text-navy">
          Product specification agreed with {lead.dealer.name}
        </p>
        <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
          <div>
            <label className="label">Agreement status</label>
            <select
              className="input"
              value={productOptionsStatus}
              onChange={(e) => setProductOptionsStatus(e.target.value as TaskStatus)}
            >
              <option value="">Not set</option>
              {TASK_OPTIONS.map((t) => (
                <option key={t} value={t}>
                  {taskStatusLabel(t, lead.dealer.name)}
                </option>
              ))}
            </select>
          </div>
          <div>
            <label className="label">Solid hoppers (0-2)</label>
            <input
              type="number"
              min="0"
              max="2"
              className="input"
              value={solidHoppers}
              onChange={(e) => setSolidHoppers(e.target.value)}
            />
          </div>
          <div>
            <label className="label">Liquid lines (1-4)</label>
            <input
              type="number"
              min="1"
              max="4"
              className="input"
              value={liquidLines}
              onChange={(e) => setLiquidLines(e.target.value)}
            />
          </div>
          <div>
            <label className="label">Flow boost</label>
            <select className="input" value={flowBoost} onChange={(e) => setFlowBoost(e.target.value)}>
              <option value="">Not set</option>
              <option value="yes">Yes</option>
              <option value="no">No</option>
            </select>
          </div>
        </div>
      </div>

      <div className="flex justify-end">
        <button className="btn-primary" disabled={saving} onClick={handleSavePipeline}>
          Save changes
        </button>
      </div>

      {error && <p className="text-sm text-red-600">{error}</p>}

      <div>
        <label className="label">Activity log</label>
        <ul className="space-y-2">
          {lead.activityLogs.length === 0 && (
            <li className="text-sm text-navy-400">No activity yet.</li>
          )}
          {lead.activityLogs.map((entry) => (
            <li key={entry.id} className="text-sm">
              <span className="text-navy-400">
                {new Date(entry.createdAt).toLocaleString()} —{" "}
              </span>
              <span className="font-medium text-navy">{entry.actor.name}</span>{" "}
              <span className="text-navy-600">{entry.action}</span>
              {entry.detail && <span className="text-navy-400"> — {entry.detail}</span>}
            </li>
          ))}
        </ul>
      </div>

      <div className="flex flex-wrap items-center gap-2 text-xs text-navy-400">
        <span>Registration:</span>
        <RegistrationBadge state={lead.registrationState} />
        <span>Stage:</span>
        <StageBadge stage={lead.stage} />
        <span>Quote:</span>
        <QuoteBadge status={lead.quoteStatus} />
      </div>
    </div>
  );
}
