"use client";

import { useState } from "react";
import { type LeadStage, type QuoteStatus, type TaskStatus } from "@prisma/client";
import {
  RegistrationBadge,
  StageBadge,
  QuoteBadge,
  STAGE_LABELS,
  QUOTE_LABELS,
  taskStatusLabel,
} from "@/components/Badges";
import { type LeadWithRelations } from "@/types/lead";

const STAGE_OPTIONS = Object.keys(STAGE_LABELS) as LeadStage[];
const QUOTE_OPTIONS = Object.keys(QUOTE_LABELS) as QuoteStatus[];
const TASK_OPTIONS: TaskStatus[] = ["DEALER_TODO", "DEALER_DONE", "CORDON_TODO", "CORDON_DONE"];

export default function LeadDetail({
  lead,
  role,
  onUpdated,
}: {
  lead: LeadWithRelations;
  role: "DEALER_USER" | "DEALER_ADMIN" | "INTERNAL_ADMIN";
  onUpdated: () => void;
}) {
  const [stage, setStage] = useState<LeadStage>(lead.stage);
  const [quoteStatus, setQuoteStatus] = useState<QuoteStatus>(lead.quoteStatus);
  const [quotedAt, setQuotedAt] = useState(lead.quotedAt ? lead.quotedAt.slice(0, 10) : "");
  const [quoteValueGbp, setQuoteValueGbp] = useState(lead.quoteValueGbp?.toString() ?? "");
  const [roiStatus, setRoiStatus] = useState<TaskStatus | "">(lead.roiStatus ?? "");
  const [productOptionsStatus, setProductOptionsStatus] = useState<TaskStatus | "">(
    lead.productOptionsStatus ?? ""
  );
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const isAdmin = role === "INTERNAL_ADMIN";

  async function patchLead(body: Record<string, unknown>) {
    setSaving(true);
    setError(null);
    const res = await fetch(`/api/leads/${lead.id}`, {
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(body),
    });
    setSaving(false);
    if (!res.ok) {
      const data = await res.json().catch(() => ({}));
      setError(data.error || "Update failed.");
      return false;
    }
    onUpdated();
    return true;
  }

  async function handleSavePipeline() {
    await patchLead({
      stage,
      quoteStatus,
      quotedAt: quotedAt ? new Date(quotedAt).toISOString() : null,
      quoteValueGbp: quoteValueGbp ? Number(quoteValueGbp) : null,
      roiStatus: roiStatus || null,
      productOptionsStatus: productOptionsStatus || null,
    });
  }

  async function handleApprove() {
    setSaving(true);
    setError(null);
    const res = await fetch(`/api/leads/${lead.id}/approve`, { method: "POST" });
    setSaving(false);
    if (!res.ok) {
      const data = await res.json().catch(() => ({}));
      setError(data.error || "Approval failed.");
      return;
    }
    onUpdated();
  }

  async function handleReject() {
    await patchLead({ registrationState: "REJECTED" });
  }

  return (
    <div className="space-y-5 border-t border-navy-100 bg-navy-50/40 p-5">
      <div className="grid gap-4 sm:grid-cols-3">
        <div>
          <label className="label">Contact</label>
          <p className="text-sm text-navy">{lead.customerName}</p>
          <p className="text-sm text-navy-400">{lead.phone || "No phone on file"}</p>
          <p className="text-sm text-navy-400">{lead.email || "No email on file"}</p>
          {lead.region && <p className="text-sm text-navy-400">{lead.region}</p>}
        </div>
        <div>
          <label className="label">Submitted by</label>
          <p className="text-sm text-navy">{lead.dealer.name}</p>
          {lead.leadGeneratorName && (
            <p className="text-sm text-navy-400">Generated by {lead.leadGeneratorName}</p>
          )}
          <p className="text-sm text-navy-400">{new Date(lead.createdAt).toLocaleString()}</p>
        </div>
        <div>
          <label className="label">Cordon status</label>
          <RegistrationBadge state={lead.registrationState} />
          {lead.expiresAt && (
            <p className="mt-1 text-xs text-navy-400">
              Exclusivity expires {new Date(lead.expiresAt).toLocaleDateString()}
            </p>
          )}
        </div>
      </div>

      {isAdmin && lead.registrationState === "PENDING" && (
        <div className="space-y-3 rounded-sm border border-orange-200 bg-orange-50 p-4">
          <p className="text-sm font-semibold text-navy">
            Approval decision needed — check for other dealers on the same vineyard.
          </p>
          <div className="flex flex-wrap gap-2">
            <button className="btn-accent" disabled={saving} onClick={handleApprove}>
              Approve (clears any conflicting registrations)
            </button>
            <button className="btn-outline" disabled={saving} onClick={handleReject}>
              Reject
            </button>
          </div>
        </div>
      )}

      <div className="grid gap-4 sm:grid-cols-2">
        <div>
          <label className="label">Client stage</label>
          <select
            className="input"
            value={stage}
            onChange={(e) => setStage(e.target.value as LeadStage)}
          >
            {STAGE_OPTIONS.map((s) => (
              <option key={s} value={s}>
                {STAGE_LABELS[s]}
              </option>
            ))}
          </select>
        </div>
        <div>
          <label className="label">Quote status</label>
          <select
            className="input"
            value={quoteStatus}
            onChange={(e) => setQuoteStatus(e.target.value as QuoteStatus)}
          >
            {QUOTE_OPTIONS.map((q) => (
              <option key={q} value={q}>
                {QUOTE_LABELS[q]}
              </option>
            ))}
          </select>
        </div>
        <div>
          <label className="label">Date quoted</label>
          <input
            type="date"
            className="input"
            value={quotedAt}
            onChange={(e) => setQuotedAt(e.target.value)}
          />
        </div>
        <div>
          <label className="label">Quote value (GBP)</label>
          <input
            type="number"
            min="0"
            step="0.01"
            className="input"
            value={quoteValueGbp}
            onChange={(e) => setQuoteValueGbp(e.target.value)}
          />
        </div>
        <div>
          <label className="label">ROI calculated with/for client?</label>
          <select
            className="input"
            value={roiStatus}
            onChange={(e) => setRoiStatus(e.target.value as TaskStatus)}
          >
            <option value="">Not set</option>
            {TASK_OPTIONS.map((t) => (
              <option key={t} value={t}>
                {taskStatusLabel(t, lead.dealer.name)}
              </option>
            ))}
          </select>
        </div>
        <div>
          <label className="label">Product options completed with client?</label>
          <select
            className="input"
            value={productOptionsStatus}
            onChange={(e) => setProductOptionsStatus(e.target.value as TaskStatus)}
          >
            <option value="">Not set</option>
            {TASK_OPTIONS.map((t) => (
              <option key={t} value={t}>
                {taskStatusLabel(t, lead.dealer.name)}
              </option>
            ))}
          </select>
        </div>
      </div>
      <div className="flex justify-end">
        <button className="btn-primary" disabled={saving} onClick={handleSavePipeline}>
          Save changes
        </button>
      </div>

      {error && <p className="text-sm text-red-600">{error}</p>}

      <div>
        <label className="label">Activity log</label>
        <ul className="space-y-2">
          {lead.activityLogs.length === 0 && (
            <li className="text-sm text-navy-400">No activity yet.</li>
          )}
          {lead.activityLogs.map((entry) => (
            <li key={entry.id} className="text-sm">
              <span className="text-navy-400">
                {new Date(entry.createdAt).toLocaleString()} —{" "}
              </span>
              <span className="font-medium text-navy">{entry.actor.name}</span>{" "}
              <span className="text-navy-600">{entry.action}</span>
              {entry.detail && <span className="text-navy-400"> — {entry.detail}</span>}
            </li>
          ))}
        </ul>
      </div>

      <div className="flex flex-wrap items-center gap-2 text-xs text-navy-400">
        <span>Registration:</span>
        <RegistrationBadge state={lead.registrationState} />
        <span>Stage:</span>
        <StageBadge stage={lead.stage} />
        <span>Quote:</span>
        <QuoteBadge status={lead.quoteStatus} />
      </div>
    </div>
  );
}
